Fix typo
knagayama/kojinki pull request #1
Opened 2019-04-06 04:45 UTC by yu5ukey

introduction.md
- [A]: Change `Aude Sapere` to `Sapere Aude`
- [B]: Add space after questions marks (except end of the lines)

lonley_rebel.md
- [C]: Drop extra declensional kana ending "し"
- [D]: Replace an English parenthesis with Japanese

2019-04-06 08:58 UTC, knagayama commented
”Aude Sapere" is intentional and is not a typo.

2019-04-06 12:23 UTC, knagayama requested changes
Aude Sapere is intentional, please keep as is

2019-04-06 20:52 UTC, yu5ukey commented
Drop unnecessary change from the previous commit.

2019-04-07 02:12 UTC, knagayama approved these changes

2019-04-07 02:12 UTC, merged